### ISSUE TITLE
Hacking Batcher format time

### ISSUE THREAD

**Issue by DezTheDapperImp** [mirkoconsiglio/Bitburner-scripts#2]
Hello again, I have been having this problem, what's strange to me is that it didn't start happening immediately after updating the scripts here or any game update I'm aware of. It reappears as soon as I click away from it, so I am unable to progress and use Cortex.js.

RUNTIME ERROR
/hacking/batcher.js@home
Args: ["sigma-cosmetics"]

formatTime is not defined
stack:
ReferenceError: formatTime is not defined
at Module.main (/hacking/batcher.js:17:29)
at executeJSScript (file:///D:/Gaming/Video%20Games/Platforms/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:19:94028)

**Comment by mirkoconsiglio** [comment]
Hi, I realised that I pushed an update that forgot to include the import of `formatTime` from `utils.js`. I just pushed an update now that should fix this. Let me know if you encounter any more bugs, thanks!
